pingcomponents = {}
pingcomponents["store"] = 1
pingcomponents["test"] = "primary"
pingcomponents["pingnumber"] = "1"
pingcomponents["prefix"] = "IP or Name"
pingcomponents["cancelled"] = "0"
pingcomponents["openfile"] = ""
pingcomponents["log"] = "Empty Log"
pingcomponents["logline"] = 0
pingcomponents["threadskilled"] = 0
pingcomponents["startupsuccessful"]=0
pingcomponents["loggingwindow"] = ""
pingcomponents["generatestats"] = 0 # created per thread
pingcomponents["pingrunningforicons"] = False
pingcomponents["startreleasedicon"] = ""
pingcomponents["pingbutton"] = ""
pingcomponents["count"] = 0
pingcomponents["threadcount"] = 0
pingcomponents["threadscomplete"] = 0
pingcomponents["rate"] = 0